'use strict';if(typeof UST!=='undefined'){alert("userTrack: [tracker.js] was included twice on this page. Please remove one instance.");}
var UST={DEBUG:false,settings:{isStatic:true,recordClick:true,recordMove:true,recordKeyboard:true,showTrackingConsent:false,delay:200,maxMoves:1170,serverPath:"//plantascarnivoras.com/espion",percentangeRecorded:100,ignoreGET:['utm_source','utm_ccc_01','gclid','utm_campaign','utm_medium'],ignoreIPs:['66.249.66.*'],minIdleTime:2,disableMobileTracking:false}};UST.randomToken=function(){return Math.random().toString(36).substr(2)+Math.random().toString(36).substr(2);};UST.enableRecord=function(){localStorage.noRecord='false';return'Recording of this device has been ENABLED.';};UST.disableRecord=function(){localStorage.noRecord='true';return'Recording of this device has been DISABLED.';};UST.randomPerc=Math.random()*100;UST.canRecord=function(){UST.isMobileDevice=(/Android|webOS|iPhone|iPad|iPod|BlackBerry/i).test(navigator.userAgent);if(UST.isMobileDevice&&UST.settings.disableMobileTracking){return false;}
if(top!==self){return false;}
if(localStorage.noRecord==='true'){return false;}
if(localStorage.getItem('token')===null){if(UST.randomPerc>=UST.settings.percentangeRecorded){UST.disableRecord();return false;}}
return true;};UST.testRequirements=function(){return'ok';};UST.getContentDiv=function(){var mostProbable=document.body;var maxP=0;var documentWidth=mostProbable.scrollWidth;var documentHeight=mostProbable.scrollHeight;var divList=document.getElementsByTagName('div');Array.prototype.forEach.call(divList,function(el){var probability=0;var style=el.currentStyle||window.getComputedStyle(el);if(style.position==='static'||style.position==='relative')
probability+=2;if(el.scrollHeight>documentHeight / 2)
probability+=3;if(el.parentElement.nodeName==='BODY')
probability++;if(style.marginLeft===style.marginRight)
probability++;if(el.getAttribute('id')==='main')
probability+=3;if(el.getAttribute('id')==='content')
probability+=2;if(el.getAttribute('id')==='container')
probability++;if(el.scrollWidth!==documentWidth)
probability+=2;if(probability>maxP){maxP=probability;mostProbable=el;}});return mostProbable;};UST.getContextPath=function(){return UST.settings.serverPath+'/';};UST.getDomain=function(){var url=document.createElement('a');url.setAttribute('href',location.href);var port=url.port?':'+url.port:'';if(document.domain.indexOf('www.')===0){return document.domain.substr(4)+port;}
return document.domain+port;};UST.removeURLParam=function(key,url){var rtn=url.split("?")[0],param,paramsArr=[],queryString=(url.indexOf("?")!==-1)?url.split("?")[1]:"";if(queryString!==""){paramsArr=queryString.split("&");for(var i=paramsArr.length-1;i>=0;i-=1){param=paramsArr[i].split("=")[0];if(param===key){paramsArr.splice(i,1);}}
rtn=rtn+"?"+paramsArr.join("&");}
return rtn;};UST.getCleanPageURL=function(){var currentURL=window.location.pathname+window.location.search;if(UST.lastURL!==currentURL){UST.lastURL=currentURL;UST.cleanPageURL=currentURL;for(var key in UST.settings.ignoreGET){var param=UST.settings.ignoreGET[key];UST.cleanPageURL=UST.removeURLParam(param,UST.cleanPageURL);if(UST.cleanPageURL[UST.cleanPageURL.length-1]==='?'){UST.cleanPageURL=UST.cleanPageURL.slice(0,-1);}}}
return UST.cleanPageURL;};!function(t){"use strict";function e(t,e){return function(o){o.target&&o.target.matches(t)&&e.apply(this,arguments)}}Element.prototype.matches||(Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector||Element.prototype.webkitMatchesSelector||function(t){for(var e=(this.document||this.ownerDocument).querySelectorAll(t),o=e.length;--o>=0&&e.item(o)!==this;);return o>-1}),t.addDynamicEventListener=function(t,o,n,r,c){t.addEventListener(o,e(n,r),c)}}(this);UST.coord4={fillZeros:function(x){x=x.toString();while(x.length<4){x='0'+x;}
return x;},get2DPoint:function(x){x=x.toString();var p={x:x.substring(0,4),y:x.substring(4)};while(p.x[0]==='0'){p.x=p.x.substring(1);}
while(p.y[0]==='0'){p.y=p.y.substring(1);}
return p;}};UST.cachedTags=[];UST.addTag=function(tag){UST.DEBUG&&console.log('Adding cached tag.',UST.cachedTags);UST.cachedTags.push(tag);};UST.DOM={ready:function(fn){if(document.attachEvent?document.readyState==="complete":document.readyState!=="loading")fn();else document.addEventListener('DOMContentLoaded',fn);},postAjax:function(url,data,success){var params=typeof data=='string'?data:Object.keys(data).map(function(k){return encodeURIComponent(k)+'='+encodeURIComponent(data[k]);}).join('&');var xhr=new XMLHttpRequest();xhr.open('POST',url);xhr.onreadystatechange=function(){if(xhr.readyState>3&&+xhr.status===200){success(xhr.responseText);}};xhr.setRequestHeader('Content-Type','application/x-www-form-urlencoded');xhr.send(params);return xhr;},offset:function(el){var rect=el.getBoundingClientRect();return{top:rect.top+document.body.scrollTop|0,left:rect.left+document.body.scrollLeft|0};},docScrollTop:function(){return(window.pageYOffset||document.documentElement.scrollTop)|0;},docScrollLeft:function(){return(window.pageXOffset||document.documentElement.scrollLeft)|0;},windowWidth:function(){return Math.max(document.documentElement.clientWidth,window.innerWidth||0)|0;},windowHeight:function(){return(window.innerHeight||document.documentElement.clientHeight)|0;},hasClass:function(elem,className){return(" "+elem.className+" ").indexOf(" "+className+" ")>-1;},getClosest:function(elem,selector){while(elem!==document.body&&elem!==document.documentElement&&elem){if(elem.matches(selector))return elem;elem=elem.parentElement;}
return null;},getUniquePath:function(element){if(element===document.documentElement){return':root';}else if(element.tagName&&element.tagName.toUpperCase()==='BODY'){return'body';}else if(element.id){return'#'+element.id;}
var parent=element.parentNode;var parentLoc=UST.DOM.getUniquePath(parent);var children=parent.childNodes;var index=0;for(var i=0;i<children.length;i++){if(children[i].nodeType===1||element.nodeType===3){if(children[i]===element){break;}
index++;}}
return parentLoc+'('+(index+1)+')';},getSelection:function(){return window.getSelection();}};UST.init=function(){UST.DEBUG&&console.log(localStorage);var errorStarting=UST.testRequirements();if(errorStarting!=='ok'){console.log('userTrack tracker could not be started.',errorStarting);return;}
if(!UST.canRecord())return;var VAL_SEPARATOR='_';var EVT_SEPARATOR='~';var KEY_SEPARATOR="`";UST.addTag=function(tag){if(typeof tag==='undefined'||tag.length===0){console.log("Tag cannot be empty!");return 0;}
UST.DOM.postAjax(getContextPath()+'addTag.php',{clientID:localStorage.getItem('clientID'),tagContent:tag},function(){UST.DEBUG&&console.log('Tag '+tag+'added');});return 1;};var getContextPath=UST.getContextPath;var getDomain=UST.getDomain;var partialLastIndex=-1;UST.ArrayToCompressedData=function(arr){if(!arr||arr.length===0)return'';return arr.join(EVT_SEPARATOR);};UST.forceSendData=function(){UST.sendDataDelay=300;clearTimeout(UST.recurseSendTimeout);recurseSend();return'Data sending has been successfully queued!';};var hadPreviousSelection=true;UST.getSelectionData=function(){setTimeout(function(){try{var selection=UST.DOM.getSelection();if(selection){if(selection.anchorNode===null){if(hadPreviousSelection){record.push('a'+KEY_SEPARATOR+'0');hadPreviousSelection=false;}
return;}
var startElPath=UST.DOM.getUniquePath(selection.anchorNode);if(selection.anchorNode.nodeType===3)startElPath=startElPath.replace(/\((\d+)\)$/g,' $1#T#');var endElPath=UST.DOM.getUniquePath(selection.focusNode);if(selection.focusNode.nodeType===3)endElPath=endElPath.replace(/\((\d+)\)$/g,' $1#T#');var selStart=selection.anchorOffset;var selEnd=selection.focusOffset;if(selStart>selEnd){var t=selStart;selStart=selEnd;selEnd=t;t=startElPath;startElPath=endElPath;endElPath=t;}
hadPreviousSelection=true;record.push('a'+KEY_SEPARATOR+
encodeURIComponent(startElPath)+
VAL_SEPARATOR+
encodeURIComponent(endElPath)+
VAL_SEPARATOR+
encodeURIComponent(selStart)+
VAL_SEPARATOR+
encodeURIComponent(selEnd));}}catch(e){console.log(e);}},10);};UST.sendData=function(clientPageID){var data={movements:'',clicks:'',partial:''};var toSend=[];for(var v in movements){var obj=UST.coord4.get2DPoint(v);obj.count=movements[v];toSend.push(obj.x+VAL_SEPARATOR+obj.y+VAL_SEPARATOR+obj.count);}
if(toSend.length>0){data.movements=toSend.join(EVT_SEPARATOR);movements={};}
toSend=[];for(v in clicks){var obj=UST.coord4.get2DPoint(v);obj.count=clicks[v];toSend.push(obj.x+VAL_SEPARATOR+obj.y+VAL_SEPARATOR+obj.count);}
if(toSend.length>0){data.clicks=toSend.join(EVT_SEPARATOR);clicks={};}
var cachedRecords=localStorage.getItem('record');if(cachedRecords!==null){cachedRecords=JSON.parse(cachedRecords);data.partial=cachedRecords.slice(partialLastIndex+1,cachedRecords.length);partialLastIndex=cachedRecords.length-1;}
if(data.movements.length||data.clicks.length||data.partial.length){UST.startDataTransferBatch(data,clientPageID);}
activityCount=0;};UST.startDataTransferBatch=function(data,clientPageID){UST.transferDataViaPixel(['m='+data.movements,'c='+data.clicks,'p='+UST.ArrayToCompressedData(data.partial)+EVT_SEPARATOR,'i='+clientPageID]);};UST.startFinalRecordTransfer=function(cachedRecords,clientPageID){UST.transferDataViaPixel(['r='+UST.ArrayToCompressedData(cachedRecords),'w=1','i='+clientPageID]);};var trackingPixelURL=getContextPath()+'/tracker/addData.php';UST.transferDataViaPixel=function(params){var trackingPixelImg=new Image();params=params.filter(function(el){return el.length>2;});trackingPixelImg.src=trackingPixelURL+'?'+params.join('&');};UST.partialToFinal=function(){var cachedRecords=localStorage.getItem('record');var clientPageID=localStorage.getItem('clientPageID');localStorage.removeItem('record');UST.DEBUG&&console.log('Trying to save final for clientPage #'+clientPageID,cachedRecords);if(cachedRecords!==null){UST.startFinalRecordTransfer(JSON.parse(cachedRecords),clientPageID);}};UST.partialToFinal();if(localStorage.getItem('token')===null||sessionStorage.getItem('activeSession')===null){localStorage.removeItem('clientID');localStorage.setItem('token',UST.randomToken());sessionStorage.setItem('activeSession','1');}
var token=localStorage.getItem('token');var lastDate=new Date();var lastActionDate=new Date();var scrollTimeout=null;var maxTimeout=3000;var movements={};var clicks={};var record=[];var activityCount=0;var lastX,lastY;var relX=0;var offsetY=0;var wpAdminBar=document.getElementById('wpadminbar');if(wpAdminBar){offsetY=-wpAdminBar.offsetHeight;}
var cachedClicks=localStorage.getItem('clicks');if(cachedClicks!==null&&cachedClicks!==undefined){clicks=JSON.parse(cachedClicks);UST.sendData(localStorage.getItem('clientPageID'));}
var clientPageID;var clientID=localStorage.getItem('clientID');UST.DOM.postAjax(getContextPath()+'tracker/createClient.php',{r:UST.DOM.windowWidth()+' '+UST.DOM.windowHeight(),t:token,u:UST.getCleanPageURL(),d:getDomain(),c:clientID,s:document.referrer,v:UST.isMobileDevice===true?1:0},function(data){UST.DEBUG&&console.log(data);if(data)data=JSON.parse(data);clientPageID=data.clientPageID;localStorage.setItem('clientPageID',clientPageID);localStorage.setItem('clientID',data.clientID);startSendingData();});UST.DOM.postAjax(getContextPath()+'helpers/clearPartial.php',{clientPageID:localStorage.getItem('clientPageID')},function(){UST.DEBUG&&console.log('partials cleared');},function(data){console.log("Could not clear partial!"+data);});if(UST.settings.isStatic){relX=UST.DOM.offset(UST.getContentDiv()).left;}
addDynamicEventListener(document.body,'click','[data-ust_click_tag]',function(e){if(!e.target)return;var tag=e.target.dataset.ust_click_tag;UST.addTag(tag);});function addIdleTime(curDate,interpTime){var idleTime=curDate-lastActionDate;if(typeof interpTime==='undefined')interpTime=0;if(idleTime>=UST.settings.minIdleTime){idleTime-=interpTime;if(idleTime>=UST.settings.minIdleTime){record.push('i'+KEY_SEPARATOR+idleTime);}}
lastActionDate=curDate;}
function handleClickEvent(e,isRightClick){if(typeof e.pageX==='undefined'||!e.target){return;}
var clickPos={x:e.pageX|0,y:e.pageY|0};if(e.pageX===e.pageY&&e.pageX===0){var offset=UST.DOM.offset(e.target);clickPos.x=offset.left+(e.target.clientWidth / 2)|0;clickPos.y=offset.top+(e.target.clientHeight / 2)|0;}
if(UST.settings.recordClick){var p=UST.coord4.fillZeros(clickPos.x-relX).toString()+UST.coord4.fillZeros(clickPos.y+offsetY);if(clicks[p]===undefined){clicks[p]=0;}
clicks[p]++;}
addIdleTime(new Date());var clickData='c'+KEY_SEPARATOR+clickPos.x+VAL_SEPARATOR+(clickPos.y+offsetY);if(isRightClick){clickData+=VAL_SEPARATOR+'R';}
record.push(clickData);localStorage.setItem('record',JSON.stringify(record));localStorage.setItem('url',UST.getCleanPageURL());activityCount+=10;if(UST.DOM.getClosest(e.target,'a')!==null){localStorage.setItem('clicks',JSON.stringify(clicks));localStorage.setItem('url',UST.getCleanPageURL());}}
document.addEventListener('click',handleClickEvent);document.addEventListener('keyup',UST.getSelectionData);document.addEventListener('mouseup',UST.getSelectionData);document.addEventListener('contextmenu',function(e){handleClickEvent(e,true);});var resizeTimeout;window.addEventListener('resize',function(){if(!resizeTimeout){resizeTimeout=setTimeout(function(){resizeTimeout=null;addCurrentWindowSize();},150);}},true);function addCurrentWindowSize(){record.push('r'+KEY_SEPARATOR+
UST.DOM.windowWidth()+
VAL_SEPARATOR+
UST.DOM.windowHeight());}
var supportsPassive=false;try{var opts=Object.defineProperty({},'passive',{get:function(){supportsPassive=true;}});window.addEventListener("test",null,opts);}catch(e){}
var lastScrollDate=undefined;window.addEventListener('scroll',function(){var now=new Date();if(lastScrollDate===undefined||now-lastScrollDate>=100){UST.DEBUG&&console.log('Scroll event recorded!');lastScrollDate=now;addIdleTime(now,100);record.push('s'+KEY_SEPARATOR+
UST.DOM.docScrollLeft()+
VAL_SEPARATOR+
UST.DOM.docScrollTop());localStorage.setItem('record',JSON.stringify(record));activityCount++;}
clearTimeout(scrollTimeout);scrollTimeout=setTimeout(function(){UST.DEBUG&&console.log('Scroll event recorded!');addIdleTime(now,100);record.push('s'+KEY_SEPARATOR+
UST.DOM.docScrollLeft()+
VAL_SEPARATOR+
UST.DOM.docScrollTop());localStorage.setItem('record',JSON.stringify(record));lastScrollDate=new Date();activityCount++;},100);},supportsPassive?{passive:true}:false);document.addEventListener('mousemove',function(e){if(typeof e.pageX==='undefined'){return;}
var curDate=new Date();var passed=curDate-lastDate;if(passed<UST.settings.delay)
return;addIdleTime(curDate,UST.settings.delay);if(--UST.settings.maxMoves>0&&passed<maxTimeout){if(lastX!==undefined&&UST.settings.recordMove){var p=UST.coord4.fillZeros(lastX).toString()+UST.coord4.fillZeros(lastY);if(!(lastX===0||lastY===0)){if(movements[p]===undefined)
movements[p]=0;movements[p]++;}}
if(!(lastX===0||lastY===0)){record.push('m'+KEY_SEPARATOR+(e.pageX|0)+VAL_SEPARATOR+(e.pageY+offsetY|0));localStorage.setItem('record',JSON.stringify(record));activityCount++;}}
lastDate=curDate;lastX=e.pageX;lastY=e.pageY+offsetY;if(UST.settings.isStatic){lastX-=relX;}});if(UST.settings.recordKeyboard){addDynamicEventListener(document.body,'focusout','input:not([type="submit"]):not([type="button"]), textarea',function(e){if(!e.target)return;var el=e.target;if(UST.DOM.hasClass(el,'noRecord')||el.type==='password')
return;addIdleTime(new Date());var uniquePath=UST.DOM.getUniquePath(el);record.push('b'+KEY_SEPARATOR+
encodeURIComponent(uniquePath)+
VAL_SEPARATOR+
encodeURIComponent(el.value));localStorage.setItem('record',JSON.stringify(record));});}
addDynamicEventListener(document,'change','select',function(e){if(!e.target)return;var el=e.target;if(UST.DOM.hasClass(el,'noRecord'))
return;var uniquePath=UST.DOM.getUniquePath(el);record.push('b'+KEY_SEPARATOR+
encodeURIComponent(uniquePath)+
VAL_SEPARATOR+
encodeURIComponent(el.value));localStorage.setItem('record',JSON.stringify(record));});function startSendingData(){while(UST.cachedTags.length){var tag=UST.cachedTags.shift();UST.addTag(tag);}
UST.sendDataDelay=300;recurseSend();}
function recurseSend(){UST.DEBUG&&console.log("Sending data for clientPageID: ",clientPageID);if(UST.sendDataDelay<4000)
UST.sendDataDelay+=400;if(UST.sendDataDelay>2000&&localStorage.getItem('record')&&activityCount>10){UST.sendDataDelay=800;}
UST.sendData(clientPageID);UST.recurseSendTimeout=setTimeout(recurseSend,UST.sendDataDelay);}};var errorMessage=UST.testRequirements();if(errorMessage!=='ok'){console.log(errorMessage);}
UST.showConfirmForm=function(text,acceptCallback,cancelCallback){var wrap=document.createElement('div');wrap.style=['background: white; border-radius: 5px; box-shadow: 0px 0px 5px rgba(0,0,0,0.2);z-index: 10001;','position: fixed; right: 20px; bottom: 20px; font-family: Arial; text-align: center; transform-origin: center right;','width: 350px;  padding: 20px; opacity: 0; transform: scaleX(0); transition: opacity 0.2s ease-out, transform 0.2s ease-out;'].join('');wrap.id='usertrack-consent';var buttonStyle='padding: 15px;background: #740e58;color: white; font-size: 16px; cursor: pointer; margin: 10px 0px; text-align: center;';var acceptButton=document.createElement('div');acceptButton.id='usertrack-consent__button';acceptButton.innerText='Accept!';acceptButton.style=buttonStyle;acceptButton.onclick=function(){acceptCallback();wrap.remove();};var link=document.createElement('a');link.style='font-size: 12px; vertical-align: center; color: #740e58;';link.href='https://docs.usertrack.net/personal-data-information.html';link.target='_blank';link.innerText='Learn more';var cancelLink=document.createElement('a');cancelLink.style='color: #a3a3a3; text-decoration: none; font-size: 12px;';cancelLink.href='#';cancelLink.innerText='No, I do not want an improved experience.';cancelLink.onclick=function(e){e.preventDefault();cancelCallback();wrap.remove();return false;};document.head.insertAdjacentHTML('beforeend','<style>#usertrack-consent__button:hover {background: #9c2477 !important;}</style>');wrap.appendChild(document.createTextNode(text));wrap.appendChild(link);wrap.appendChild(acceptButton);wrap.appendChild(cancelLink);document.body.appendChild(wrap);setTimeout(function(){wrap.style.opacity=1;wrap.style.transform='scaleX(1)';},100);};UST.isIPignored=function(ip){var otherIP,i,ipParts,otherParts,match,partIdx,lastPart,currentPart;for(i=0;i<UST.settings.ignoreIPs.length;++i){otherIP=UST.settings.ignoreIPs[i];if(otherIP===ip){return true;}
ipParts=ip.split('.');otherParts=otherIP.split('.');lastPart=undefined;match=true;for(partIdx=0;partIdx<ipParts.length;++partIdx){currentPart=otherParts[partIdx];if(currentPart===undefined&&lastPart==='*'){currentPart='*';}
if(ipParts[partIdx]!==currentPart&&currentPart!=='*'){match=false;break;}
lastPart=currentPart;}
if(match){return true;}}
return false;};UST.start=function(){if(UST.canRecord&&UST.settings.ignoreIPs&&UST.settings.ignoreIPs.length>0&&UST.settings.ignoreIPs[0]!==''){var head=document.getElementsByTagName('head')[0];var script=document.createElement('script');script.type='text/javascript';script.src=UST.getContextPath()+'helpers/getIP.php';var initCalled=false;script.onreadystatechange=script.onload=function(){if(initCalled)return;initCalled=true;if(UST.settings.ignoreIPs.indexOf(ust_myIP)===-1){UST.init();}else{UST.disableRecord();}};head.appendChild(script);}else{UST.init();}};UST.DOM.ready(function(){if(localStorage.ustGDPRaccepted==='false'||!UST.canRecord()){return;}
if(!UST.settings.showTrackingConsent||localStorage.ustGDPRaccepted==='true'){UST.start();}else{UST.showConfirmForm('This site can store session data in order to improve your experience. ',function(){localStorage.ustGDPRaccepted='true';UST.start();},function(){localStorage.ustGDPRaccepted='false';});}});if(top!==self){(function(){var head=document.getElementsByTagName('head')[0];if(typeof jQuery==='undefined'){var jqScriptTag=document.createElement('script');jqScriptTag.type='text/javascript';jqScriptTag.async=false;jqScriptTag.src=UST.getContextPath()+'lib/jquery.1.12.4.min.js';head.appendChild(jqScriptTag);}
var script=document.createElement('script');script.type='text/javascript';script.async=false;script.src=UST.getContextPath()+'tracker/inject.js';head.appendChild(script);})();}